apps/basket/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.BasketView.as_view(), name='summary'),
    url(r'^add/(?P<pk>\d+)/$', views.BasketAddView.as_view(), name='add'),
    url(r'^vouchers/add/$', views.VoucherAddView.as_view(),
        name='vouchers-add'),
    url(r'^vouchers/(?P<pk>\d+)/remove/$',
        views.VoucherRemoveView.as_view(), name='vouchers-remove'),
    url(r'^saved/$', login_required(views.SavedView.as_view()),
        name='saved'),
]

apps/checkout/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Shipping/user address views
    url(r'shipping-address/$',
        views.ShippingAddressView.as_view(), name='shipping-address'),
    url(r'user-address/edit/(?P<pk>\d+)/$',
        views.UserAddressUpdateView.as_view(),
        name='user-address-update'),
    url(r'user-address/delete/(?P<pk>\d+)/$',
        views.UserAddressDeleteView.as_view(),
        name='user-address-delete'),

    # Shipping method views
    url(r'shipping-method/$',
        views.ShippingMethodView.as_view(), name='shipping-method'),

    # Payment views
    url(r'payment-method/$',
        views.PaymentMethodView.as_view(), name='payment-method'),
    url(r'payment-details/$',
        views.PaymentDetailsView.as_view(), name='payment-details'),
    #
    # # Preview and thankyou
    url(r'preview/$',
        views.PaymentDetailsView.as_view(preview=True),
        name='preview'),
    url(r'thank-you/$', views.ThankYouView.as_view(),
        name='thank-you'),
]



def get_url_decorator(self, pattern):
    if not settings.FURNITURE_ALLOW_ANON_CHECKOUT:
        return login_required
    if pattern.name.startswith('user-address'):
        return login_required
    return None

furniture/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

from views.decorators import login_forbidden
from apps.customer.forms import PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=settings.HOME_PAGE_URL, permanent=False)),
    url(r'^catalogue/', include('apps.catalogue.urls', namespace='catalogue')),
    url(r'^customer/', include('apps.customer.urls', namespace='customer')),
    url(r'^basket/', include('apps.basket.urls', namespace='basket')),
    url(r'^checkout/', include('apps.checkout.urls', namespace='checkout')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^offer/', include('apps.offer.urls', namespace='offer')),
    url(r'^promotion/', include('apps.promotions.urls', namespace='promotions')),
    url(r'^search/', include('apps.search.urls', namespace='search')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password-reset/$',
        login_forbidden(auth_views.password_reset),
        {'password_reset_form': PasswordResetForm,
         'post_reset_redirect': reverse_lazy('password-reset-done')},
        name='password-reset'),
    url(r'^password-reset/done/$',
        login_forbidden(auth_views.password_reset_done),
        name='password-reset-done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        login_forbidden(auth_views.password_reset_confirm),
        {
            'post_reset_redirect': reverse_lazy('password-reset-complete'),
            'set_password_form': SetPasswordForm,
        },
        name='password-reset-confirm'),
    url(r'^password-reset/complete/$',
        login_forbidden(auth_views.password_reset_complete),
        name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/basket/views.py
import json

from django import shortcuts
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.utils.http import is_safe_url
from django.utils.translation import ugettext_lazy as _
from django.views.generic import FormView, View
from extra_views import ModelFormSetView

from apps.basket.signals import (
    basket_addition, voucher_addition, voucher_removal)
from core import ajax
from core.compat import user_is_authenticated
from core.loading import get_class, get_classes, get_model
from core.utils import redirect_to_referrer, safe_referrer

Applicator = get_class('offer.applicator', 'Applicator')
(BasketLineForm, AddToBasketForm, BasketVoucherForm, SavedLineForm) = get_classes(
    'basket.forms', ('BasketLineForm', 'AddToBasketForm',
                     'BasketVoucherForm', 'SavedLineForm'))
BasketLineFormSet, SavedLineFormSet = get_classes(
    'basket.formsets', ('BasketLineFormSet', 'SavedLineFormSet'))
Repository = get_class('shipping.repository', 'Repository')

OrderTotalCalculator = get_class(
    'checkout.calculators', 'OrderTotalCalculator')
BasketMessageGenerator = get_class('basket.utils', 'BasketMessageGenerator')


class BasketView(ModelFormSetView):
    model = get_model('basket', 'Line')
    basket_model = get_model('basket', 'Basket')
    formset_class = BasketLineFormSet
    form_class = BasketLineForm
    extra = 0
    can_delete = True
    template_name = 'basket/basket.html'

    def get_formset_kwargs(self):
        kwargs = super(BasketView, self).get_formset_kwargs()
        kwargs['strategy'] = self.request.strategy
        return kwargs

    def get_queryset(self):
        return self.request.basket.all_lines()

    def get_shipping_methods(self, basket):
        return Repository().get_shipping_methods(
            basket=self.request.basket, user=self.request.user,
            request=self.request)

    def get_default_shipping_method(self, basket):
        return Repository().get_default_shipping_method(
            basket=self.request.basket, user=self.request.user,
            request=self.request)

    def get_basket_warnings(self, basket):
        """
        Return a list of warnings that apply to this basket
        """
        warnings = []
        for line in basket.all_lines():
            warning = line.get_warning()
            if warning:
                warnings.append(warning)
        return warnings

    def get_upsell_messages(self, basket):
        offers = Applicator().get_offers(basket, self.request.user,
                                         self.request)
        applied_offers = list(basket.offer_applications.offers.values())
        msgs = []
        for offer in offers:
            if offer.is_condition_partially_satisfied(basket) \
                    and offer not in applied_offers:
                data = {
                    'message': offer.get_upsell_message(basket),
                    'offer': offer}
                msgs.append(data)
        return msgs

    def get_basket_voucher_form(self):
        """
        This is a separate method so that it's easy to e.g. not return a form
        if there are no vouchers available.
        """
        return BasketVoucherForm()

    def get_context_data(self, **kwargs):
        context = super(BasketView, self).get_context_data(**kwargs)
        context['voucher_form'] = self.get_basket_voucher_form()

        # Shipping information is included to give an idea of the total order
        # cost.  It is also important for PayPal Express where the customer
        # gets redirected away from the basket page and needs to see what the
        # estimated order total is beforehand.
        context['shipping_methods'] = self.get_shipping_methods(
            self.request.basket)
        method = self.get_default_shipping_method(self.request.basket)
        context['shipping_method'] = method
        shipping_charge = method.calculate(self.request.basket)
        context['shipping_charge'] = shipping_charge
        if method.is_discounted:
            excl_discount = method.calculate_excl_discount(self.request.basket)
            context['shipping_charge_excl_discount'] = excl_discount

        context['order_total'] = OrderTotalCalculator().calculate(
            self.request.basket, shipping_charge)
        context['basket_warnings'] = self.get_basket_warnings(
            self.request.basket)
        context['upsell_messages'] = self.get_upsell_messages(
            self.request.basket)

        if user_is_authenticated(self.request.user):
            try:
                saved_basket = self.basket_model.saved.get(
                    owner=self.request.user)
            except self.basket_model.DoesNotExist:
                pass
            else:
                saved_basket.strategy = self.request.basket.strategy
                if not saved_basket.is_empty:
                    saved_queryset = saved_basket.all_lines()
                    formset = SavedLineFormSet(strategy=self.request.strategy,
                                               basket=self.request.basket,
                                               queryset=saved_queryset,
                                               prefix='saved')
                    context['saved_formset'] = formset
        return context

    def get_success_url(self):
        return safe_referrer(self.request, 'basket:summary')

    def formset_valid(self, formset):
        # Store offers before any changes are made so we can inform the user of
        # any changes
        offers_before = self.request.basket.applied_offers()
        save_for_later = False

        # Keep a list of messages - we don't immediately call
        # django.contrib.messages as we may be returning an AJAX response in
        # which case we pass the messages back in a JSON payload.
        flash_messages = ajax.FlashMessages()

        for form in formset:
            if (hasattr(form, 'cleaned_data') and
                    form.cleaned_data['save_for_later']):
                line = form.instance
                if user_is_authenticated(self.request.user):
                    self.move_line_to_saved_basket(line)

                    msg = render_to_string(
                        'basket/messages/line_saved.html',
                        {'line': line})
                    flash_messages.info(msg)

                    save_for_later = True
                else:
                    msg = _("You can't save an item for later if you're "
                            "not logged in!")
                    flash_messages.error(msg)
                    return redirect(self.get_success_url())

        if save_for_later:
            # No need to call super if we're moving lines to the saved basket
            response = redirect(self.get_success_url())
        else:
            # Save changes to basket as per normal
            response = super(BasketView, self).formset_valid(formset)

        # If AJAX submission, don't redirect but reload the basket content HTML
        if self.request.is_ajax():
            # Reload basket and apply offers again
            self.request.basket = get_model('basket', 'Basket').objects.get(
                id=self.request.basket.id)
            self.request.basket.strategy = self.request.strategy
            Applicator().apply(self.request.basket, self.request.user,
                               self.request)
            offers_after = self.request.basket.applied_offers()

            for level, msg in BasketMessageGenerator().get_messages(
                    self.request.basket, offers_before, offers_after, include_buttons=False):
                flash_messages.add_message(level, msg)

            # Reload formset - we have to remove the POST fields from the
            # kwargs as, if they are left in, the formset won't construct
            # correctly as there will be a state mismatch between the
            # management form and the database.
            kwargs = self.get_formset_kwargs()
            del kwargs['data']
            del kwargs['files']
            if 'queryset' in kwargs:
                del kwargs['queryset']
            formset = self.get_formset()(queryset=self.get_queryset(),
                                         **kwargs)
            ctx = self.get_context_data(formset=formset,
                                        basket=self.request.basket)
            return self.json_response(ctx, flash_messages)

        BasketMessageGenerator().apply_messages(self.request, offers_before)

        return response

    def json_response(self, ctx, flash_messages):
        basket_html = render_to_string(
            'basket/partials/basket_content.html',
            context=ctx, request=self.request)

        payload = {
            'content_html': basket_html,
            'messages': flash_messages.as_dict()}
        return HttpResponse(json.dumps(payload),
                            content_type="application/json")

    def move_line_to_saved_basket(self, line):
        saved_basket, _ = get_model('basket', 'basket').saved.get_or_create(
            owner=self.request.user)
        saved_basket.merge_line(line)

    def formset_invalid(self, formset):
        flash_messages = ajax.FlashMessages()
        flash_messages.warning(_(
            "Your basket couldn't be updated. "
            "Please correct any validation errors below."))

        if self.request.is_ajax():
            ctx = self.get_context_data(formset=formset,
                                        basket=self.request.basket)
            return self.json_response(ctx, flash_messages)

        flash_messages.apply_to_request(self.request)
        return super(BasketView, self).formset_invalid(formset)


class BasketAddView(FormView):
    """

templates/basket/partials/basket_content.html
{% load i18n %}
{% load thumbnail %}
{% load currency_filters %}
{% load purchase_info_tags %}
{% load widget_tweaks %}

{% if basket_warnings %}
    <h5>{% trans "Important messages about items in your basket" %}</h5>
    {% for warning in basket_warnings %}
        <div class="alert alert-warning">{{ warning }}</div>
    {% endfor %}
{% endif %}

{% if upsell_messages %}
    <div class="well">
        <h3>{% trans "You could be missing out on offers!" %}</h3>
        {% for upsell in upsell_messages %}
            {% blocktrans with message=upsell.message url=upsell.offer.get_absolute_url offer_name=upsell.offer.name %}
                <div class="warning">{{ message }} to qualify for the <a href="{{ url }}">{{ offer_name }}</a> special offer</div>
            {% endblocktrans %}
        {% endfor %}
    </div>
{% endif %}

{% if not basket.is_empty %}
    {% block basket_form_headers %}
        <div class="basket-title hidden-xs">
            <div class="row">
                <h2 class="col-sm-6 h3">{% trans "Items to buy now" %}</h2>
                <p class="col-sm-3 h3">{% trans "Quantity" %}</p>
                <p class="col-sm-1 h3 align-right">{% trans "Price" %}</p>
                <p class="col-sm-2 h3 align-right">{% trans "Total" %}</p>
            </div>
        </div>
    {% endblock %}

    {% block basket_form_main %}
        <form action="." method="post" class="basket_summary" id="basket_formset">
            {% csrf_token %}
            {{ formset.management_form }}

            {% for form in formset %}
                {% with line=form.instance product=form.instance.product %}
                    {% purchase_info_for_line request line as session %}
                    <div class="basket-items">
                        <div class="row">
                            <div class="col-sm-2">
                                {{ form.id }}
                                {% with image=product.primary_image %}
                                    {% thumbnail image.original "100x100" upscale=False as thumb %}
                                        <a href="{{ product.get_absolute_url }}">
                                            <img class="thumbnail" src="{{ thumb.url }}" alt="{{ product.get_title }}"/>
                                        </a>
                                    {% endthumbnail %}
                                {% endwith %}
                            </div>
                            <div class="col-sm-4">
                                <h3><a href="{{ product.get_absolute_url }}">{{ line.description }}</a></h3>
                                <p class="availability {{ session.availability.code }}">{{ session.availability.message }}</p>
                            </div>
                            <div class="col-sm-3">
                                <div class="checkout-quantity">
                                    <div class="input-group  {% if form.errors %}error{% endif %}">
                                        {% render_field form.quantity class+="form-control" %}
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit" data-loading-text="{% trans 'Updating...' %}">{% trans "Update" %}</button>
                                    </span>
                                    </div>
                                </div>
                                    <div>
                                        <a href="#" data-id="{{ forloop.counter0 }}" data-behaviours="remove" class="inline">{% trans "Remove" %}</a>
                                        {% if user.is_authenticated %}
                                            | <a href="#" data-id="{{ forloop.counter0 }}" data-behaviours="save" class="inline">{% trans "Save for later" %}</a>
                                        {% endif %}
                                        <div style="display:none">
                                            {{ form.save_for_later }}
                                            {{ form.DELETE }}
                                        </div>
                                        {% for field_errors in form.errors.values %}
                                            {% for error in field_errors %}
                                                <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                                            {% endfor %}

                                        {% endfor %}
                                    </div>

                            </div>
                            <div class="col-sm-1">
                                {% if not line.unit_price_incl_tax and not line.unit_tax_excl_tax %}
                                    <p class="align-right">&mdash;</p>
                                {% else %}
                                    <p class="price_color align-right">
                                        {% if line.is_tax_known %}
                                            {{ line.unit_price_incl_tax|currency:line.price_currency }}
                                        {% else %}
                                            {{ line.unit_price_excl_tax|currency:line.price_currency }}
                                        {% endif %}
                                    </p>
                                {% endif %}
                            </div>
                            <div class="col-sm-2">
                                {% if not line.line_price_incl_tax and not line_price_excl_tax %}
                                    <p class="align-right">&mdash;</p>
                                {% else %}
                                    <p class="price_color align-right">
                                        {% if line.is_tax_known %}
                                            {{ line.line_price_incl_tax|currency:line.price_currency }}
                                        {% else %}
                                            {{ line.line_price_excl_tax|currency:line.price_currency }}
                                        {% endif %}
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </form>
    {% endblock %}

    <div class="row">
        {% block vouchers %}
            {# Hide the entire section if a custom BasketView doesn't pass in a voucher form #}
            {% if voucher_form %}
                <div class="col-sm-6">
                    <div class="sub-header">
                        <h2>{% trans "Voucher/promo code" %}</h2>
                    </div>
                    <p id="voucher_form_link"><a href="#voucher" class="btn btn-default btn-full">{% trans "I have a voucher code..." %}</a></p>

                    <div id="voucher_form_container" style="display:none">
                        <form id="voucher_form" action="{% url 'basket:vouchers-add' %}" method="post">
                            {% csrf_token %}
                            {% include "partials/form_fields.html" with form=voucher_form %}
                            <button type="submit" class="btn btn-info" data-loading-text="{% trans 'Adding...' %}">{% trans "Add voucher" %}</button>
                            {% trans "or" %} <a href="#" id="voucher_form_cancel">{% trans "cancel" %}</a>
                        </form>
                    </div>
                </div>
            {% endif %}
        {% endblock vouchers %}

        {% block baskettotals %}
            <div class="col-sm-6">
                <div class="sub-header">
                    <h2>{% trans "Totals" %}</h2>
                </div>
                {% include 'basket/partials/basket_totals.html' with editable=1 %}
            </div>
        {% endblock baskettotals %}
    </div>


    {% block formactions %}
        <div class="form-group clearfix">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8">
                    <a href="{% url 'checkout:index' %}" class="btn btn-lg btn-primary btn-block">{% trans "Proceed to checkout" %}</a>
                </div>
            </div>
        </div>
    {% endblock formactions %}

{% else %}
    {% block emptybasket %}
        <p>
            {% trans "Your basket is empty." %}
            <a href="{{ homepage_url }}">{% trans "Continue shopping" %}</a>
        </p>
    {% endblock %}
{% endif %}

{% block savedbasket %}
    {% if user.is_authenticated and saved_formset %}
        <div class="well">
            <div class="sub-header">
                <h2>{% trans "Items to buy later" %}</h2>
            </div>
            <div class="row basket-title hidden-xs">
                <p class="col-sm-8 h4">{% trans "Items" %}</p>
                <p class="col-sm-2 h4 align-center">{% trans "Price" %}</p>
                <div class="col-sm-2">&nbsp;</div>
            </div>
            <form action="{% url 'basket:saved' %}" method="post" class="form-stacked later_summary" id="saved_basket_formset">
                {% csrf_token %}
                {{ saved_formset.management_form }}
                {% for form in saved_formset %}
                    {% purchase_info_for_product request form.instance.product as session %}
                    <div class="basket-items">
                        <div class="row">
                            <div class="col-sm-2">
                                {{ form.id }}
                                {% with image=form.instance.product.primary_image %}
                                    {% thumbnail image.original "100x100" upscale=False as thumb %}
                                        <a href="{{ form.instance.product.get_absolute_url }}">
                                            <img class="thumbnail" src="{{ thumb.url }}" alt="{{ form.instance.product.get_title }}">
                                        </a>
                                    {% endthumbnail %}
                                {% endwith %}
                            </div>
                            <div class="col-sm-6">
                                <h3><a href="{{ form.instance.product.get_absolute_url }}">{{ form.instance.description }}</a></h3>
                                <p class="availability {{ session.availability.code }}">{{ session.availability.message }}</p>
                                <a href="#" data-id="{{ forloop.counter0 }}" data-behaviours="remove">{% trans "Remove" %}</a>
                                <div style="display:none">
                                    {{ form.move_to_basket }}
                                    {{ form.DELETE }}
                                </div>
                            </div>
                            {% purchase_info_for_product request form.instance.product as saved %}
                            <div class="col-sm-2 align-center">
                                <p class="price_color">
                                    {% if saved.price.is_tax_known %}
                                        {{ saved.price.incl_tax|currency:saved.price.currency }}
                                    {% else %}
                                        {{ saved.price.excl_tax|currency:saved.price.currency }}
                                    {% endif %}
                                </p>
                            </div>
                            <div class="col-sm-2">
                                <a href="#" data-id="{{ forloop.counter0 }}" class="btn pull-right btn-block" data-behaviours="move">{% trans "Move to basket" %}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </form>
        </div>
    {% endif %}
{% endblock %}

templates/basket/partials/basket_quick.html
{% load history_tags %}
{% load basket_tags %}
{% load currency_filters %}
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

<div class="container">
  <div class="shopping-cart" style="display:none;">
    <div class="shopping-cart-header">
      <i class="icon-shopping-cart"></i><span class="badge">3</span>
      <div class="shopping-cart-total">
        <span class="lighter-text">{% trans "Total:" %}</span>
        {% if request.basket.is_tax_known %}
            <span class="main-color-text">{{ request.basket.total_incl_tax|currency:request.basket.currency }}</span>
        {% else %}
            <span class="main-color-text">{{ request.basket.total_excl_tax|currency:request.basket.currency }}</span>
        {% endif %}
      </div>
    </div> <!--end shopping-cart-header -->

    <ul class="shopping-cart-items">
      {% if request.basket.num_lines %}
          {% for line in request.basket.all_lines %}
            <li class="clearfix">
              {% with image=line.product.primary_image %}
                  {% thumbnail image.original "100x100" upscale=False as thumb %}
                  <a href="{{ line.product.get_absolute_url }}"><img class="thumbnail" src="{{ thumb.url }}" alt="{{ line.product.get_title }}"></a>
                  {% endthumbnail %}
              {% endwith %}
              <span class="item-name">
                <a href="{{ line.product.get_absolute_url }}">{{ line.description }}</a>
              </span>
              <span class="item-price">
                {{ line.unit_price_excl_tax|currency:request.basket.currency }}
              </span>
              <span class="item-quantity">{{ line.quantity }}</span>
            </li>
          {% endfor %}
      {% else %}
          <li><p>{% trans "Your basket is empty." %}</p></li>
      {% endif %}
    </ul>

    <a href="#" class="button">Checkout</a>
  </div> <!--end shopping-cart -->
</div> <!--end container -->