apps/basket/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.BasketView.as_view(), name='summary'),
    url(r'^add/(?P<pk>\d+)/$', views.BasketAddView.as_view(), name='add'),
    url(r'^vouchers/add/$', views.VoucherAddView.as_view(),
        name='vouchers-add'),
    url(r'^vouchers/(?P<pk>\d+)/remove/$',
        views.VoucherRemoveView.as_view(), name='vouchers-remove'),
    url(r'^saved/$', login_required(views.SavedView.as_view()),
        name='saved'),
]

apps/catalogue/reviews/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ProductReviewDetail.as_view(),
        name='reviews-detail'),
    url(r'^add/$', views.CreateProductReview.as_view(),
        name='reviews-add'),
    url(r'^(?P<pk>\d+)/vote/$',
        login_required(views.AddVoteView.as_view()),
        name='reviews-vote'),
    url(r'^$', views.ProductReviewList.as_view(), name='reviews-list'),
]

apps/catalogue/urls.py
from django.conf.urls import url, include

from . import views
from .reviews import urls as review_urls
from apps.offer.views import RangeDetailView

urlpatterns = [
    # url(r'^$', views.home, name="home"),
    url(r'^$', views.CatalogueView.as_view(), name="index"),
    url(r'^(?P<slug>[\w-]*)/(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name="product-detail"),
    url(r'^category/(?P<category_slug>[\w-]+(/[\w-]+)*)_(?P<pk>\d+)/$', views.ProductCategoryView.as_view(), name="category"),
    url(r'^category/(?P<category_slug>[\w-]+(/[\w-]+)*)/$', views.ProductCategoryView.as_view()),
    url(r'^ranges/(?P<slug>[\w-]+)/$', RangeDetailView.as_view(), name="range"),
    url(r'^(?P<product_slug>[\w-]*)_(?P<product_pk>\d+)/reviews/', include('apps.catalogue.reviews.urls'))
]

apps/customer/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views import generic

from .notifications import views as notification_views
from .alerts import views as alert_views
from .wishlists import views as wishlists_views
from . import views

urlpatterns = [
    url(r'^login/$', views.AccountAuthView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.AccountRegistrationView.as_view(), name='register'),
    url(r'^$', login_required(views.AccountSummaryView.as_view()),
        name='summary'),
    url(r'^change-password/$',
        login_required(views.ChangePasswordView.as_view()),
        name='change-password'),

    # Profile
    url(r'^profile/$',
        login_required(views.ProfileView.as_view()),
        name='profile-view'),
    url(r'^profile/edit/$',
        login_required(views.ProfileUpdateView.as_view()),
        name='profile-update'),
    url(r'^profile/delete/$',
        login_required(views.ProfileDeleteView.as_view()),
        name='profile-delete'),

    # Order history
    url(r'^orders/$',
        login_required(views.OrderHistoryView.as_view()),
        name='order-list'),
    url(r'^order-status/(?P<order_number>[\w-]*)/(?P<hash>\w+)/$',
        views.AnonymousOrderDetailView.as_view(), name='anon-order'),
    url(r'^orders/(?P<order_number>[\w-]*)/$',
        login_required(views.OrderDetailView.as_view()),
        name='order'),
    url(r'^orders/(?P<order_number>[\w-]*)/(?P<line_id>\d+)$',
        login_required(views.OrderLineView.as_view()),
        name='order-line'),

    # Address book
    url(r'^addresses/$',
        login_required(views.AddressListView.as_view()),
        name='address-list'),
    url(r'^addresses/add/$',
        login_required(views.AddressCreateView.as_view()),
        name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$',
        login_required(views.AddressUpdateView.as_view()),
        name='address-detail'),
    url(r'^addresses/(?P<pk>\d+)/delete/$',
        login_required(views.AddressDeleteView.as_view()),
        name='address-delete'),
    url(r'^addresses/(?P<pk>\d+)/'
        r'(?P<action>default_for_(billing|shipping))/$',
        login_required(views.AddressChangeStatusView.as_view()),
        name='address-change-status'),

    # Email history
    url(r'^emails/$',
        login_required(views.EmailHistoryView.as_view()),
        name='email-list'),
    url(r'^emails/(?P<email_id>\d+)/$',
        login_required(views.EmailDetailView.as_view()),
        name='email-detail'),

    # Notifications
    # Redirect to notification inbox
    url(r'^notifications/$', generic.RedirectView.as_view(
        url='/accounts/notifications/inbox/', permanent=False)),
    url(r'^notifications/inbox/$',
        login_required(notification_views.InboxView.as_view()),
        name='notifications-inbox'),
    url(r'^notifications/archive/$',
        login_required(notification_views.ArchiveView.as_view()),
        name='notifications-archive'),
    url(r'^notifications/update/$',
        login_required(notification_views.UpdateView.as_view()),
        name='notifications-update'),
    url(r'^notifications/(?P<pk>\d+)/$',
        login_required(notification_views.DetailView.as_view()),
        name='notifications-detail'),

    # Alerts
    # Alerts can be setup by anonymous users: some views do not
    # require login
    url(r'^alerts/$',
        login_required(alert_views.ProductAlertListView.as_view()),
        name='alerts-list'),
    url(r'^alerts/create/(?P<pk>\d+)/$',
        alert_views.ProductAlertCreateView.as_view(),
        name='alert-create'),
    url(r'^alerts/confirm/(?P<key>[a-z0-9]+)/$',
        alert_views.ProductAlertConfirmView.as_view(),
        name='alerts-confirm'),
    url(r'^alerts/cancel/key/(?P<key>[a-z0-9]+)/$',
        alert_views.ProductAlertCancelView.as_view(),
        name='alerts-cancel-by-key'),
    url(r'^alerts/cancel/(?P<pk>[a-z0-9]+)/$',
        login_required(alert_views.ProductAlertCancelView.as_view()),
        name='alerts-cancel-by-pk'),

    # Wishlists
    url(r'wishlists/$',
        login_required(wishlists_views.WishListListView.as_view()),
        name='wishlists-list'),
    url(r'wishlists/add/(?P<product_pk>\d+)/$',
        login_required(wishlists_views.WishListAddProduct.as_view()),
        name='wishlists-add-product'),
    url(r'wishlists/(?P<key>[a-z0-9]+)/add/(?P<product_pk>\d+)/',
        login_required(wishlists_views.WishListAddProduct.as_view()),
        name='wishlists-add-product'),
    url(r'wishlists/create/$',
        login_required(wishlists_views.WishListCreateView.as_view()),
        name='wishlists-create'),
    url(r'wishlists/create/with-product/(?P<product_pk>\d+)/$',
        login_required(wishlists_views.WishListCreateView.as_view()),
        name='wishlists-create-with-product'),
    # Wishlists can be publicly shared, no login required
    url(r'wishlists/(?P<key>[a-z0-9]+)/$',
        wishlists_views.WishListDetailView.as_view(), name='wishlists-detail'),
    url(r'wishlists/(?P<key>[a-z0-9]+)/update/$',
        login_required(wishlists_views.WishListUpdateView.as_view()),
        name='wishlists-update'),
    url(r'wishlists/(?P<key>[a-z0-9]+)/delete/$',
        login_required(wishlists_views.WishListDeleteView.as_view()),
        name='wishlists-delete'),
    url(r'wishlists/(?P<key>[a-z0-9]+)/lines/(?P<line_pk>\d+)/delete/',
        login_required(wishlists_views.WishListRemoveProduct.as_view()),
        name='wishlists-remove-product'),
    url(r'wishlists/(?P<key>[a-z0-9]+)/products/(?P<product_pk>\d+)/'
        r'delete/',
        login_required(wishlists_views.WishListRemoveProduct.as_view()),
        name='wishlists-remove-product'),
    url(r'wishlists/(?P<key>[a-z0-9]+)/lines/(?P<line_pk>\d+)/move-to/'
        r'(?P<to_key>[a-z0-9]+)/$',
        login_required(wishlists_views.WishListMoveProductToAnotherWishList
                       .as_view()),
        name='wishlists-move-product-to-another')
]

furniture/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

from views.decorators import login_forbidden
from apps.customer.forms import PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=settings.HOME_PAGE_URL, permanent=False)),
    url(r'^catalogue/', include('apps.catalogue.urls', namespace='catalogue')),
    url(r'^customer/', include('apps.customer.urls', namespace='customer')),
    url(r'^basket/', include('apps.basket.urls', namespace='basket')),
    url(r'^checkout/', include('apps.checkout.urls', namespace='checkout')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^offer/', include('apps.offer.urls', namespace='offer')),
    url(r'^promotion/', include('apps.promotions.urls', namespace='promotions')),
    url(r'^search/', include('apps.search.urls', namespace='search')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password-reset/$',
        login_forbidden(auth_views.password_reset),
        {'password_reset_form': PasswordResetForm,
         'post_reset_redirect': reverse_lazy('password-reset-done')},
        name='password-reset'),
    url(r'^password-reset/done/$',
        login_forbidden(auth_views.password_reset_done),
        name='password-reset-done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        login_forbidden(auth_views.password_reset_confirm),
        {
            'post_reset_redirect': reverse_lazy('password-reset-complete'),
            'set_password_form': SetPasswordForm,
        },
        name='password-reset-confirm'),
    url(r'^password-reset/complete/$',
        login_forbidden(auth_views.password_reset_complete),
        name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/catalogue/reviews/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from core.loading import get_model

Vote = get_model('reviews', 'vote')
ProductReview = get_model('reviews', 'productreview')


class ProductReviewForm(forms.ModelForm):
    name = forms.CharField(label=_('Name'), required=True)
    email = forms.EmailField(label=_('Email'), required=True)

    def __init__(self, product, user=None, *args, **kwargs):
        super(ProductReviewForm, self).__init__(*args, **kwargs)
        self.instance.product = product
        if user and user.is_authenticated:
            self.instance.user = user
            del self.fields['name']
            del self.fields['email']

    class Meta:
        model = ProductReview
        fields = ('title', 'score', 'body', 'name', 'email')


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = ('delta',)

    def __init__(self, review, user, *args, **kwargs):
        super(VoteForm, self).__init__(*args, **kwargs)
        self.instance.review = review
        self.instance.user = user

    @property
    def is_up_vote(self):
        return self.cleaned_data['delta'] == Vote.UP

    @property
    def is_down_vote(self):
        return self.cleaned_data['delta'] == Vote.DOWN


class SortReviewsForm(forms.Form):
    SORT_BY_SCORE = 'score'
    SORT_BY_RECENCY = 'recency'
    SORT_REVIEWS_BY_CHOICES = (
        (SORT_BY_SCORE, _('Score')),
        (SORT_BY_RECENCY, _('Recency')),
    )

    sort_by = forms.ChoiceField(
        choices=SORT_REVIEWS_BY_CHOICES,
        label=_('Sort by'),
        initial=SORT_BY_SCORE,
    )

apps/catalogue/reviews/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, DetailView, ListView, View

from apps.catalogue.reviews.signals import review_added
from core.loading import get_classes, get_model
from core.utils import redirect_to_referrer

ProductReviewForm, VoteForm, SortReviewsForm = get_classes(
    'catalogue.reviews.forms',
    ['ProductReviewForm', 'VoteForm', 'SortReviewsForm'])

Vote = get_model('reviews', 'vote')
ProductReview = get_model('reviews', 'ProductReview')
Product = get_model('catalogue', 'product')


class CreateProductReview(CreateView):
    template_name = "catalogue/reviews/review_form.html"
    model = ProductReview
    product_model = Product
    form_class = ProductReviewForm
    view_signal = review_added

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(
            self.product_model, pk=kwargs['product_pk'])
        # check permission to leave review
        if not self.product.is_review_permitted(request.user):
            if self.product.has_review_by(request.user):
                message = _("You have already reviewed this product!")
            else:
                message = _("You can't leave a review for this product.")
            messages.warning(self.request, message)
            return redirect(self.product.get_absolute_url())

        return super(CreateProductReview, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateProductReview, self).get_context_data(**kwargs)
        context['product'] = self.product
        return context

    def get_form_kwargs(self):
        kwargs = super(CreateProductReview, self).get_form_kwargs()
        kwargs['product'] = self.product
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        response = super(CreateProductReview, self).form_valid(form)
        self.send_signal(self.request, response, self.object)
        return response

    def get_success_url(self):
        messages.success(
            self.request, _("Thank you for reviewing this product"))
        return self.product.get_absolute_url()

    def send_signal(self, request, response, review):
        self.view_signal.send(sender=self, review=review, user=request.user,
                              request=request, response=response)


class ProductReviewDetail(DetailView):
    template_name = "catalogue/reviews/review_detail.html"
    context_object_name = 'review'
    model = ProductReview

    def get_context_data(self, **kwargs):
        context = super(ProductReviewDetail, self).get_context_data(**kwargs)
        context['product'] = get_object_or_404(
            Product, pk=self.kwargs['product_pk'])
        return context


class AddVoteView(View):
    """
    Simple view for voting on a review.

    We use the URL path to determine the product and review and use a 'delta'
    POST variable to indicate it the vote is up or down.
    """

    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=self.kwargs['product_pk'])
        review = get_object_or_404(ProductReview, pk=self.kwargs['pk'])

        form = VoteForm(review, request.user, request.POST)
        if form.is_valid():
            if form.is_up_vote:
                review.vote_up(request.user)
            elif form.is_down_vote:
                review.vote_down(request.user)
            messages.success(request, _("Thanks for voting!"))
        else:
            for error_list in form.errors.values():
                for msg in error_list:
                    messages.error(request, msg)
        return redirect_to_referrer(request, product.get_absolute_url())


class ProductReviewList(ListView):
    """
    Browse reviews for a product
    """
    template_name = 'catalogue/reviews/review_list.html'
    context_object_name = "reviews"
    model = ProductReview
    product_model = Product
    paginate_by = settings.FURNITURE_REVIEWS_PER_PAGE

    def get_queryset(self):
        qs = self.model.objects.approved().filter(product=self.kwargs['product_pk'])
        self.form = SortReviewsForm(self.request.GET)
        if self.form.is_valid():
            sort_by = self.form.cleaned_data['sort_by']
            if sort_by == SortReviewsForm.SORT_BY_RECENCY:
                return qs.order_by('-date_created')
        return qs.order_by('-score')

    def get_context_data(self, **kwargs):
        context = super(ProductReviewList, self).get_context_data(**kwargs)
        context['product'] = get_object_or_404(
            self.product_model, pk=self.kwargs['product_pk'])
        context['form'] = self.form
        return context

templates/catalogue/partials/add_to_basket_form.html
{% load basket_tags %}
{% load display_tags %}
{% load i18n %}
{% load purchase_info_tags %}

{% purchase_info_for_product request product as session %}

{% if session.availability.is_available_to_buy %}
    {% basket_form request product as basket_form %}
    <form id="add_to_basket_form" action="{% url 'basket:add' pk=product.pk  %}" method="post" class="add-to-basket">
        {% csrf_token %}
        {% include "partials/form_fields.html" with form=basket_form %}
        <button type="submit" class="btn btn-lg btn-primary btn-add-to-basket" value="{% trans "Add to basket" %}" data-loading-text="{% trans 'Adding...' %}">{% trans "Add to basket" %}</button>
    </form>
    {% iffeature "wishlists" %}
        {% include "catalogue/partials/add_to_wishlist.html" %}
    {% endiffeature %}
{% else %}
    {% if has_active_alert %}
        <p>{% trans "You have an active stock alert for this product." %}</p>
    {% else %}
        <form id="alert_form" method="post" action="{% url 'customer:alert-create' pk=product.id %}" class="add-to-basket">
            {% csrf_token %}
            <p>{% trans "You can get an email alert when this product is back in stock." %}</p>
            {% include "partials/form_fields.html" with form=alert_form %}
            <button type="submit" class="btn btn-lg btn-info btn-add-to-basket" data-loading-text="{% trans 'Submitting...' %}">{% trans "Notify me" %}</button>
        </form>
    {% endif %}
    {% iffeature "wishlists" %}
        {% include "catalogue/partials/add_to_wishlist.html" %}
    {% endiffeature %}
{% endif %}

templates/catalogue/partials/add_to_basket_form_compact.html
{% load basket_tags %}
{% load i18n %}
{% load purchase_info_tags %}

{% purchase_info_for_product request product as session %}

{% if session.availability.is_available_to_buy %}
    {% basket_form request product 'single' as basket_form %}
    <form action="{% url 'basket:add' pk=product.pk %}" method="post">
        {% csrf_token %}
        {{ basket_form.as_p }}
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="{% trans 'Adding...' %}">{% trans "Add to basket" %}</button>
    </form>
{% else %}
    <span class="btn btn-default btn-block disabled">{% trans "Add to basket" %}</span>
{% endif %}

templates/catalogue/partials/add_to_wishlist.html
{% load i18n %}
{% load wishlist_tags %}

{% if user.is_authenticated %}
    {% with wishlists=user.wishlists.all %}
        {# Select wishlists that contains product #}
        {% wishlists_containing_product wishlists product as product_wishlists %}
        {% if wishlists %}

            <div class="btn-group btn-wishlist">
                <a class="btn btn-lg dropdown-toggle" data-toggle="dropdown" href="#">{% trans "Add to wish list" %} <span class="caret"></span></a>
                <ul class="dropdown-menu pull-right">
                    {% for wishlist in wishlists %}
                        {% if wishlist not in product_wishlists %}
                            <li>
                                    <a href="{% url 'customer:wishlists-add-product' key=wishlist.key product_pk=product.pk %}">
                                        {% blocktrans with name=wishlist.name %}
                                            Add to '{{ name }}' wish list
                                        {% endblocktrans %}
                                    </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <li><a href="{% url 'customer:wishlists-create-with-product' product_pk=product.pk %}">{% trans 'Create a new wishlist' %}</a></li>
                </ul>
            </div>
        {% else %}
            {# 1 or no existing wishlists - show a simple button #}
            <form id="add_to_wishlist_form" action="{% url 'customer:wishlists-add-product' product_pk=product.pk %}" method="post" class="btn-wishlist">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg" data-loading-text="{% trans 'Adding...' %}">{% trans "Add to wish list" %}</button>
            </form>
        {% endif %}

        {% for wishlist in product_wishlists %}
            <form action="{% url 'customer:wishlists-remove-product' key=wishlist.key product_pk=product.id %}" method="post">
                {% csrf_token %}
                {% blocktrans with name=wishlist.name url=wishlist.get_absolute_url %}
                    <span class="pull-left">Product is in <a href="{{ url }}">'{{ name }}'</a> wishlist.</span>
                {% endblocktrans %}
                <button type="submit" class="btn btn-sm pull-right" data-loading-text="{% trans 'Removing...' %}">{% trans "Remove" %}</button>
            </form>
        {% endfor %}
    {% endwith %}
{% else %}
    <button class="btn btn-lg btn-wishlist" disabled="disabled" title="{% trans 'Please login to add products to a wish list.' %}">{% trans 'Add to wish list' %}</button><br/>
{% endif %}

templates/catalogue/partials/gallery.html
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

{% with all_images=product.get_all_images %}
    {# use length rather then count as the images get queried anyways #}

    {% if all_images|length > 1 %}

        <div id="product_gallery" class="carousel slide">

            <div class="thumbnail">
                <div class="carousel-inner" role="listbox">
                {% for image in all_images %}
                    <div class="item {% if forloop.first %}active{% endif %}">
                        {% thumbnail image.original "440x400" upscale=False as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                        {% endthumbnail %}
                    </div>
                {% endfor %}
                </div>
                <a class="carousel-control left" href="#product_gallery" role="button" data-slide="prev">
                    <span class="icon-prev fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-angle-left fa-stack-1x"></i>
                    </span>
                </a>
                <a class="carousel-control right" href="#product_gallery" role="button" data-slide="next">
                    <span class="icon-next fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-angle-right fa-stack-1x"></i>
                    </span>
                </a>
            </div>

            <ol class="carousel-indicators thumbnail">
                {% for image in all_images %}
                    <li data-target="#product_gallery" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}">
                        {% thumbnail image.original "65x55" crop="center" as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                        {% endthumbnail %}
                    </li>
                {% endfor %}
            </ol>
        </div>

    {% else %}

        {# Only one image to show #}
        <div id="product_gallery" class="carousel">
            <div class="thumbnail">
                <div class="carousel-inner">
                    <div class="item active">
                    {% with image=product.primary_image %}
                        {% thumbnail image.original "440x400" upscale=False as thumb %}
                            <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                        {% endthumbnail %}
                    {% endwith %}
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endwith %}

templates/catalogue/partials/product.html
{% load reviews_tags %}
{% load thumbnail %}
{% load i18n %}
{% load display_tags %}
{% load staticfiles %}


{% block product %}
    <div class="card">
      <div class="card-header">
        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
          <ul class="list-inline mb-0">
            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="card-content collapse show" style="">
        {% block product_image %}
            <div class="image_container">
                {% with image=product.primary_image %}
                    {% thumbnail image.original "x155" upscale=False as thumb %}
                    <a hrezf="{{ product.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ product.get_title }}" class="card-img-top img-fluid"></a>
                    {% endthumbnail %}
                {% endwith %}
            </div>
        {% endblock %}
        <div class="card-body">
          {% block product_title %}
              <h4 class="card-title">
                <a href="{{ product.get_absolute_url }}" title="{{ product.get_title }}">{{ product.get_title|truncatewords:4 }}</a>
              </h4>
              {% block product_review %}
                  {% iffeature "reviews" %}
                      <p class="star-rating {{ product.rating|as_stars }}">
                          <i class="icon-star"></i>
                          <i class="icon-star"></i>
                          <i class="icon-star"></i>
                          <i class="icon-star"></i>
                          <i class="icon-star"></i>
                      </p>
                  {% endiffeature %}
              {% endblock %}
          {% endblock %}
        </div>
        <div class="card-footer text-muted">
          {% block product_price %}
              <span class="float-left product_price">
                  {% include "catalogue/partials/stock_record.html" %}
              </span>
              <span class="float-right">
                {% if not product.is_parent %}
                    {% include "catalogue/partials/add_to_basket_form_compact.html" %}
                {% endif %}
              </span>
          {% endblock %}
        </div>
      </div>
    </div>
{% endblock %}

templates/catalogue/partials/review.html
{% load reviews_tags %}
{% load i18n %}

<article class="review">
    <header>
        <h3 class="star-rating {{ review.score|as_stars }}">
            <span>
                <i class="icon-star"></i>
                <i class="icon-star"></i>
                <i class="icon-star"></i>
                <i class="icon-star"></i>
                <i class="icon-star"></i>
            </span>
            <a href="{{ review.get_absolute_url }}">{{ review.title }}</a>
        </h3>
    </header>

    <p>{{ review.body|striptags }}</p>

    <p>
        <small>
            {% if review.user == user %}
                {% blocktrans with review_date=review.date_created %}
                Reviewed by you on {{ review_date }}
                {% endblocktrans %}
            {% else %}
                {% blocktrans with name=review.reviewer_name review_date=review.date_created %}
                    Reviewed by <strong>{{ name }}</strong> on {{ review_date }}
                {% endblocktrans %}
            {% endif %}
            | <a href="{% url 'catalogue:reviews-detail' product_slug=product.slug product_pk=product.pk pk=review.pk %}">{% trans 'Permalink' %}</a>
        </small>
    </p>

    {% if review|may_vote:user %}
        <small>{% trans "Is this review helpful?" %}</small>
        <form action="{% url 'catalogue:reviews-vote' product_slug=product.slug product_pk=product.pk pk=review.pk %}" method="post" class="vote_agree" >
            {% csrf_token %}
            <input type="hidden" name="delta" value="1"/>
            <button type="submit" class="btn btn-success btn-xs" data-loading-text="{% trans 'Submitting...' %}">{% trans "Yes" %}</button>
        </form>
        <form  action="{% url 'catalogue:reviews-vote' product_slug=product.slug product_pk=product.pk pk=review.pk %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="delta" value="-1"/>
            <button type="submit" class="btn btn-danger btn-xs" data-loading-text="{% trans 'Submitting...' %}">{% trans "No" %}</button>
        </form>
    {% endif %}
             
    <p>   
        <small>
        {% if review.has_votes %}
            {% blocktrans with num_up_votes=review.num_up_votes count num_votes=review.total_votes %}
            <strong>{{ num_up_votes }}</strong> of {{ num_votes }} customer found this useful
            {% plural %}
            <strong>{{ num_up_votes }}</strong> of {{ num_votes }} customers found this useful
            {% endblocktrans %}
        {% else %}
            {% trans "This review has no votes." %}
        {% endif %}
        </small>
    </p>
</article>

templates/catalogue/partials/stock_record.html
{% load currency_filters %}
{% load i18n %}
{% load purchase_info_tags %}

{% purchase_info_for_product request product as session %}

{% if session.price.exists %}
    {% if session.price.excl_tax == 0 %}
        <p class="price_color">{% trans "Free" %}</p>
    {% elif session.price.is_tax_known %}
        <p class="price_color">{{ session.price.incl_tax|currency:session.price.currency }}</p>
    {% else %}
        <p class="price_color">{{ session.price.excl_tax|currency:session.price.currency }}</p>
    {% endif %}
{% else %}
    <p class="price_color">&nbsp;</p>
{% endif %}
<p class="{{ session.availability.code }} availability">
    <i class="icon-{% if session.availability.is_available_to_buy %}ok{% else %}remove{% endif %}"></i>
    {% if verbose %}
        {{ session.availability.message }}
    {% else %}
        {{ session.availability.short_message }}
    {% endif %}
</p>