apps/catalogue/reviews/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ProductReviewDetail.as_view(),
        name='reviews-detail'),
    url(r'^add/$', views.CreateProductReview.as_view(),
        name='reviews-add'),
    url(r'^(?P<pk>\d+)/vote/$',
        login_required(views.AddVoteView.as_view()),
        name='reviews-vote'),
    url(r'^$', views.ProductReviewList.as_view(), name='reviews-list'),
]

apps/catalogue/urls.py
from django.conf.urls import url, include

from . import views
from .reviews import urls as review_urls
from apps.offer.views import RangeDetailView

urlpatterns = [
    # url(r'^$', views.home, name="home"),
    url(r'^$', views.CatalogueView.as_view(), name="index"),
    url(r'^(?P<slug>[\w-]*)/(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name="product-detail"),
    url(r'^category/(?P<category_slug>[\w-]+(/[\w-]+)*)_(?P<pk>\d+)/$', views.ProductCategoryView.as_view(), name="category"),
    url(r'^category/(?P<category_slug>[\w-]+(/[\w-]+)*)/$', views.ProductCategoryView.as_view()),
    url(r'^ranges/(?P<slug>[\w-]+)/$', RangeDetailView.as_view(), name="range"),
    url(r'^(?P<product_slug>[\w-]*)_(?P<product_pk>\d+)/reviews/', include('apps.catalogue.reviews.urls'))
]

apps/dashboard/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

from core.loading import get_class
# from . import views

index_view = get_class('dashboard.views', 'IndexView')
reports_app = get_class('dashboard.reports.app', 'application')
orders_app = get_class('dashboard.orders.app', 'application')
users_app = get_class('dashboard.users.app', 'application')
catalogue_app = get_class('dashboard.catalogue.app', 'application')
promotions_app = get_class('dashboard.promotions.app', 'application')
pages_app = get_class('dashboard.pages.app', 'application')
partners_app = get_class('dashboard.partners.app', 'application')
offers_app = get_class('dashboard.offers.app', 'application')
ranges_app = get_class('dashboard.ranges.app', 'application')
reviews_app = get_class('dashboard.reviews.app', 'application')
vouchers_app = get_class('dashboard.vouchers.app', 'application')
comms_app = get_class('dashboard.communications.app', 'application')
shipping_app = get_class('dashboard.shipping.app', 'application')

urlpatterns = [
    url(r'^$', index_view.as_view(), name='index'),
    url(r'^catalogue/', catalogue_app.urls),
    url(r'^reports/', reports_app.urls),
    url(r'^orders/', orders_app.urls),
    url(r'^users/', users_app.urls),
    url(r'^content-blocks/', promotions_app.urls),
    url(r'^pages/', pages_app.urls),
    url(r'^partners/', partners_app.urls),
    url(r'^offers/', offers_app.urls),
    url(r'^ranges/', ranges_app.urls),
    url(r'^reviews/', reviews_app.urls),
    url(r'^vouchers/', vouchers_app.urls),
    url(r'^comms/', comms_app.urls),
    url(r'^shipping/', shipping_app.urls),

    url(r'^login/$', auth_views.login, {
        'template_name': 'dashboard/login.html',
        'authentication_form': AuthenticationForm,
    }, name='login'),
    url(r'^logout/$', auth_views.logout, {
        'next_page': '/',
    }, name='logout'),
]

furniture/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

from views.decorators import login_forbidden
from apps.customer.forms import PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=settings.HOME_PAGE_URL, permanent=False)),
    url(r'^catalogue/', include('apps.catalogue.urls', namespace='catalogue')),
    url(r'^customer/', include('apps.customer.urls', namespace='customer')),
    url(r'^basket/', include('apps.basket.urls', namespace='basket')),
    url(r'^checkout/', include('apps.checkout.urls', namespace='checkout')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^offer/', include('apps.offer.urls', namespace='offer')),
    url(r'^promotion/', include('apps.promotions.urls', namespace='promotions')),
    url(r'^search/', include('apps.search.urls', namespace='search')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password-reset/$',
        login_forbidden(auth_views.password_reset),
        {'password_reset_form': PasswordResetForm,
         'post_reset_redirect': reverse_lazy('password-reset-done')},
        name='password-reset'),
    url(r'^password-reset/done/$',
        login_forbidden(auth_views.password_reset_done),
        name='password-reset-done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        login_forbidden(auth_views.password_reset_confirm),
        {
            'post_reset_redirect': reverse_lazy('password-reset-complete'),
            'set_password_form': SetPasswordForm,
        },
        name='password-reset-confirm'),
    url(r'^password-reset/complete/$',
        login_forbidden(auth_views.password_reset_complete),
        name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/catalogue/reviews/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from core.loading import get_model

Vote = get_model('reviews', 'vote')
ProductReview = get_model('reviews', 'productreview')


class ProductReviewForm(forms.ModelForm):
    name = forms.CharField(label=_('Name'), required=True)
    email = forms.EmailField(label=_('Email'), required=True)

    def __init__(self, product, user=None, *args, **kwargs):
        super(ProductReviewForm, self).__init__(*args, **kwargs)
        self.instance.product = product
        if user and user.is_authenticated:
            self.instance.user = user
            del self.fields['name']
            del self.fields['email']

    class Meta:
        model = ProductReview
        fields = ('title', 'score', 'body', 'name', 'email')


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = ('delta',)

    def __init__(self, review, user, *args, **kwargs):
        super(VoteForm, self).__init__(*args, **kwargs)
        self.instance.review = review
        self.instance.user = user

    @property
    def is_up_vote(self):
        return self.cleaned_data['delta'] == Vote.UP

    @property
    def is_down_vote(self):
        return self.cleaned_data['delta'] == Vote.DOWN


class SortReviewsForm(forms.Form):
    SORT_BY_SCORE = 'score'
    SORT_BY_RECENCY = 'recency'
    SORT_REVIEWS_BY_CHOICES = (
        (SORT_BY_SCORE, _('Score')),
        (SORT_BY_RECENCY, _('Recency')),
    )

    sort_by = forms.ChoiceField(
        choices=SORT_REVIEWS_BY_CHOICES,
        label=_('Sort by'),
        initial=SORT_BY_SCORE,
    )

apps/dashboard/catalogue/forms.py
from django import forms
from django.core import exceptions
from django.utils.translation import ugettext_lazy as _
from treebeard.forms import movenodeform_factory

from core.loading import get_class, get_model
from core.utils import slugify
from forms.widgets import DateTimePickerInput, ImageInput

Product = get_model('catalogue', 'Product')
ProductClass = get_model('catalogue', 'ProductClass')
ProductAttribute = get_model('catalogue', 'ProductAttribute')
Category = get_model('catalogue', 'Category')
StockRecord = get_model('partner', 'StockRecord')
ProductCategory = get_model('catalogue', 'ProductCategory')
ProductImage = get_model('catalogue', 'ProductImage')
ProductRecommendation = get_model('catalogue', 'ProductRecommendation')
AttributeOptionGroup = get_model('catalogue', 'AttributeOptionGroup')
AttributeOption = get_model('catalogue', 'AttributeOption')
ProductSelect = get_class('dashboard.catalogue.widgets', 'ProductSelect')
RelatedFieldWidgetWrapper = get_class('dashboard.widgets',
                                      'RelatedFieldWidgetWrapper')

CategoryForm = movenodeform_factory(
    Category,
    fields=['name', 'description', 'image'])


class ProductClassSelectForm(forms.Form):
    """
    Form which is used before creating a product to select it's product class
    """

    product_class = forms.ModelChoiceField(
        label=_("Create a new product of type"),
        empty_label=_("-- Choose type --"),
        queryset=ProductClass.objects.all())

    def __init__(self, *args, **kwargs):
        """
        If there's only one product class, pre-select it
        """
        super(ProductClassSelectForm, self).__init__(*args, **kwargs)
        qs = self.fields['product_class'].queryset
        if not kwargs.get('initial') and len(qs) == 1:
            self.fields['product_class'].initial = qs[0]


class ProductSearchForm(forms.Form):
    upc = forms.CharField(max_length=16, required=False, label=_('UPC'))
    name = forms.CharField(
        max_length=255, required=False, label=_('Product name'))

    def clean(self):
        cleaned_data = super(ProductSearchForm, self).clean()
        cleaned_data['upc'] = cleaned_data['upc'].strip()
        cleaned_data['name'] = cleaned_data['name'].strip()
        return cleaned_data


class StockRecordForm(forms.ModelForm):

    def __init__(self, product_class, user, *args, **kwargs):
        # The user kwarg is not used by stock StockRecordForm. We pass it
        # anyway in case one wishes to customise the partner queryset
        self.user = user
        super(StockRecordForm, self).__init__(*args, **kwargs)

        # Restrict accessible partners for non-staff users
        if not self.user.is_staff:
            self.fields['partner'].queryset = self.user.partners.all()

        # If not tracking stock, we hide the fields
        if not product_class.track_stock:
            for field_name in ['num_in_stock', 'low_stock_treshold']:
                if field_name in self.fields:
                    del self.fields[field_name]
        else:
            for field_name in ['price_excl_tax', 'num_in_stock']:
                if field_name in self.fields:
                    self.fields[field_name].required = True

    class Meta:
        model = StockRecord
        fields = [
            'partner', 'partner_sku',
            'price_currency', 'price_excl_tax', 'price_retail', 'cost_price',
            'num_in_stock', 'low_stock_threshold',
        ]


def _attr_text_field(attribute):
    return forms.CharField(label=attribute.name,
                           required=attribute.required)


def _attr_textarea_field(attribute):
    return forms.CharField(label=attribute.name,
                           widget=forms.Textarea(),
                           required=attribute.required)


def _attr_integer_field(attribute):
    return forms.IntegerField(label=attribute.name,
                              required=attribute.required)


def _attr_boolean_field(attribute):
    return forms.BooleanField(label=attribute.name,
                              required=attribute.required)


def _attr_float_field(attribute):
    return forms.FloatField(label=attribute.name,
                            required=attribute.required)


def _attr_date_field(attribute):
    return forms.DateField(label=attribute.name,
                           required=attribute.required,
                           widget=forms.widgets.DateInput)


def _attr_datetime_field(attribute):
    return forms.DateTimeField(label=attribute.name,
                               required=attribute.required,
                               widget=DateTimePickerInput())


def _attr_option_field(attribute):
    return forms.ModelChoiceField(
        label=attribute.name,
        required=attribute.required,
        queryset=attribute.option_group.options.all())


def _attr_multi_option_field(attribute):
    return forms.ModelMultipleChoiceField(
        label=attribute.name,
        required=attribute.required,
        queryset=attribute.option_group.options.all())


def _attr_entity_field(attribute):
    # Product entities don't have out-of-the-box supported in the ProductForm.
    # There is no ModelChoiceField for generic foreign keys, and there's no
    # good default behaviour anyway; offering a choice of *all* model instances
    # is hardly useful.
    return None


def _attr_numeric_field(attribute):
    return forms.FloatField(label=attribute.name,
                            required=attribute.required)


def _attr_file_field(attribute):
    return forms.FileField(
        label=attribute.name, required=attribute.required)


def _attr_image_field(attribute):
    return forms.ImageField(
        label=attribute.name, required=attribute.required)


class ProductForm(forms.ModelForm):
    FIELD_FACTORIES = {
        "text": _attr_text_field,
        "richtext": _attr_textarea_field,
        "integer": _attr_integer_field,
        "boolean": _attr_boolean_field,
        "float": _attr_float_field,
        "date": _attr_date_field,
        "datetime": _attr_datetime_field,
        "option": _attr_option_field,
        "multi_option": _attr_multi_option_field,
        "entity": _attr_entity_field,
        "numeric": _attr_numeric_field,
        "file": _attr_file_field,
        "image": _attr_image_field,
    }

    class Meta:
        model = Product
        fields = [
            'name', 'upc', 'description', 'is_discountable', 'structure']
        widgets = {
            'structure': forms.HiddenInput()
        }

    def __init__(self, product_class, data=None, parent=None, *args, **kwargs):
        self.set_initial(product_class, parent, kwargs)
        super(ProductForm, self).__init__(data, *args, **kwargs)
        if parent:
            self.instance.parent = parent
            # We need to set the correct product structures explicitly to pass
            # attribute validation and child product validation. Note that
            # those changes are not persisted.
            self.instance.structure = Product.CHILD
            self.instance.parent.structure = Product.PARENT

            self.delete_non_child_fields()
        else:
            # Only set product class for non-child products
            self.instance.product_class = product_class
        self.add_attribute_fields(product_class, self.instance.is_parent)

        if 'name' in self.fields:
            self.fields['name'].widget = forms.TextInput(
                attrs={'autocomplete': 'off'})

    def set_initial(self, product_class, parent, kwargs):
        """
        Set initial data for the form. Sets the correct product structure
        and fetches initial values for the dynamically constructed attribute
        fields.
        """
        if 'initial' not in kwargs:
            kwargs['initial'] = {}
        self.set_initial_attribute_values(product_class, kwargs)
        if parent:
            kwargs['initial']['structure'] = Product.CHILD

    def set_initial_attribute_values(self, product_class, kwargs):
        """
        Update the kwargs['initial'] value to have the initial values based on
        the product instance's attributes
        """
        instance = kwargs.get('instance')
        if instance is None:
            return
        for attribute in product_class.attributes.all():
            try:
                value = instance.attribute_values.get(
                    attribute=attribute).value
            except exceptions.ObjectDoesNotExist:
                pass
            else:
                kwargs['initial']['attr_%s' % attribute.code] = value

    def add_attribute_fields(self, product_class, is_parent=False):
        """
        For each attribute specified by the product class, this method
        dynamically adds form fields to the product form.
        """
        for attribute in product_class.attributes.all():
            field = self.get_attribute_field(attribute)
            if field:
                self.fields['attr_%s' % attribute.code] = field
                # Attributes are not required for a parent product
                if is_parent:
                    self.fields['attr_%s' % attribute.code].required = False

    def get_attribute_field(self, attribute):
        """
        Gets the correct form field for a given attribute type.
        """
        return self.FIELD_FACTORIES[attribute.type](attribute)

    def delete_non_child_fields(self):
        """
        Deletes any fields not needed for child products. Override this if
        you want to e.g. keep the description field.
        """
        for field_name in ['description', 'is_discountable']:
            if field_name in self.fields:
                del self.fields[field_name]

    def _post_clean(self):
        """
        Set attributes before ModelForm calls the product's clean method
        (which it does in _post_clean), which in turn validates attributes.
        """
        self.instance.attr.initiate_attributes()

templates/dashboard/catalogue/attribute_option_group_delete.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}

{% block title %}
    {{ title }} | {% trans "Create Attribute Option Group" %} | {{ block.super }}
{% endblock %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block navbar %}
{% if not is_popup %}
    {{ block.super }}
{% endif %}
{% endblock %}

{% block dashboard_nav %}
{% if not is_popup %}
    {{ block.super }}
{% endif %}
{% endblock %}

{% block breadcrumbs %}
{% if not is_popup %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
        <a href="{% url 'dashboard:catalogue-attribute-option-group-list' %}">{% trans "Attribute Option Group" %}</a>
    </li>
    <li class="active">{% trans "Delete Attribute Option Group?" %}</li>
</ul>
{% endif %}
{% endblock %}

{% block headertext %}
    {{ title }}
{% endblock %}

{% block dashboard_content %}
    {% if disallow %}
        <p>{% trans "Please make sure all Product Attributes are assigned to another Attribute Option Group before deletion." %}</p>
    {% else %}
        <div class="table-header">
            <h2>{% trans "Delete Attribute Option Group" %}</h2>
        </div>
        <form action="." method="post" class="well">
            {% csrf_token %}
            {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
            {% if not is_popup %}
            {% for key, value in http_get_params.items %}
                <input type="hidden" name="{{ key }}" value="{{ value }}" />
            {% endfor %}
            {% endif %}
            <p>
                {% blocktrans with name=object.name %}Delete Attribute Option Group <strong>{{ name }}</strong> - are you sure?{% endblocktrans %}
            </p>
            <div class="form-actions">
                <a {% if not is_popup %}href="{% url 'dashboard:catalogue-attribute-option-group-list' %}"{% else %}href="#" onclick="window.close();return false;"{% endif %}>
                    {% trans "Cancel" %}
                </a>
                <button type="submit" class="btn btn-danger" data-loading-text="{% trans 'Deleting...' %}">
                    {% trans "Delete" %}
                </button>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/dashboard/catalogue/attribute_option_group_form.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}

{% block title %}
    {{ title }} | {% trans "Create Attribute Option Group" %} | {{ block.super }}
{% endblock %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block navbar %}
{% if not is_popup %}
    {{ block.super }}
{% endif %}
{% endblock %}

{% block dashboard_nav %}
{% if not is_popup %}
    {{ block.super }}
{% endif %}
{% endblock %}

{% block breadcrumbs %}
{% if not is_popup %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:catalogue-attribute-option-group-list' %}">{% trans "Attribute Option Group" %}</a>
        </li>
        <li class="active">{{ title }}</li>
    </ul>
{% endif %}
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <form class="form-stacked wysiwyg fixed-actions" method="post" data-behaviour="affix-nav-errors">
        {% csrf_token %}

        <div class="row">
            {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="{{ is_popup }}" />{% endif %}
            {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}

            {% block tab_nav %}
                <div class="col-md-3">
                    <div data-spy="affix" class="affix-top" data-offset-top="200">
                        <div class="table-header">
                            <h3>{% trans "Sections" %}</h3>
                        </div>
                        <ul class="nav nav-list bs-docs-sidenav" id="attribute_option_group_update_tabs">

                            {% block tabs %}
                                <li class="active"><a href="#attribute_option_group_details" data-toggle="tab">{% trans 'Attribute Option Group details' %}</a></li>
                                <li><a href="#attribute_options" data-toggle="tab">{% trans 'Attribute Options' %}</a></li>

                            {% endblock tabs %}
                        </ul>
                    </div>
                </div>
            {% endblock tab_nav %}

            <div class="col-md-9">
                <div class="tab-content">
                    {% block tab_content %}
                        {% block attribute_option_group_details %}
                            <div class="tab-pane active" id="attribute_option_group_details">
                                <div class="table-header">
                                    <h3>{% trans "Attribute Option Group details" %}</h3>
                                </div>
                                <div class="well attribute-option-group-details">

                                    {% comment %}
                                        If the AttributeOptionGroup form has field_errors, partials/form_fields.html
                                        will render an error message.
                                        This means that there'll be 2 error messages,
                                        one from the partial and one from the view. Perhaps there should be
                                        an option allowing hiding of the error message in the template.
                                        For now we copy paste what we need from the template.
                                    {% endcomment %}

                                    {% if form.non_field_errors %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-error control-group error">
                                                <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                                            </div>
                                        {% endfor %}
                                    {% endif %}

                                    {% for field in form %}
                                        {% include 'dashboard/partials/form_field.html' with field=field %}
                                    {% endfor %}
                                </div>
                            </div>
                        {% endblock %}

                        {% block attribute_options %}
                            <div class="tab-pane" id="attribute_options">
                                <div class="table-header">
                                    <h3>{% trans "Attribute Options" %}</h3>
                                </div>
                                <div class="attribute-options">
                                    <table class="table table-striped table-bordered">
                                        {{ attribute_option_formset.management_form }}
                                        {{ attribute_option_formset.non_form_errors }}
                                        <col width="50%">
                                        <col width="50%">
                                        <thead>
                                            <tr>
                                                <th>{% trans "Option" %}</th>
                                                <th>{% trans "Delete?" %}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for attribute_option_form in attribute_option_formset %}
                                                <tr>
                                                    {% for hidden_field in attribute_option_form.hidden_fields %}
                                                        {{ hidden_field }}
                                                    {% endfor %}
                                                    <td>{% include 'dashboard/partials/form_field.html' with field=attribute_option_form.option nolabel=True %}</td>
                                                    <td>{% include 'dashboard/partials/form_field.html' with field=attribute_option_form.DELETE nolabel=True %}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% endblock %}
                    {% endblock tab_content %}
                </div>
            </div>
        </div>

        {% block fixed_actions_group %}
            <div class="fixed-actions-group">
                <div class="form-actions">
                    <div class="pull-right">
                        <a href="#" {% if not is_popup %}onclick="window.history.go(-1);return false"{% else %}onclick="window.close();return false;"{% endif %}>
                            {% trans "Cancel" %}
                        </a>
                        {% trans "or" %}
                        <button class="btn btn-large btn-primary" type="submit">
                            {% trans "Save" %}
                        </button>
                    </div>
                </div>
            </div>
        {% endblock fixed_actions_group %}
    </form>

{% endblock dashboard_content %}

{% block onbodyload %}
    {{ block.super }}
    oscar.dashboard.product_attributes.init();
{% endblock %}

templates/dashboard/catalogue/attribute_option_group_list.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block title %}
    {% trans "Attribute Option Groups" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">{% trans "Attribute Option Group" %}</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header">
        <a href="{% url 'dashboard:catalogue-attribute-option-group-create' %}?{{ querystring }}" class="btn btn-primary btn-lg pull-right"><i class="icon-plus"></i> {% trans "Create new Attribute Option Group" %}</a>
        <h1>{% trans "Attribute Option Group" %}</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% if attribute_option_groups %}
        {% block product_list %}
            <form action="." method="post">
                {% csrf_token %}
                {% render_table attribute_option_groups %}
            </form>
        {% endblock product_list %}
    {% else %}
        <p>{% trans "No Attribute Option Groups found." %}</p>
    {% endif %}
{% endblock dashboard_content %}

templates/dashboard/catalogue/attribute_option_group_row_actions.html
{% load django_tables2 %}
{% load i18n %}
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
            {% trans "Actions" %}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="{% url 'dashboard:catalogue-attribute-option-group-update' pk=record.id %}{% querystring %}">{% trans "Edit Attribute Option Group" %}</a>
            </li>
            <li>
                <a href="{% url 'dashboard:catalogue-attribute-option-group-delete' pk=record.id %}{% querystring %}">{% trans "Delete" %}</a>
            </li>
        </ul>
    </div>
</div>

templates/dashboard/catalogue/attribute_option_group_row_name.html
{% load django_tables2 %}
<a href="{% url 'dashboard:catalogue-attribute-option-group-update' pk=record.pk %}{% querystring %}">{{ value }}</a>

templates/dashboard/catalogue/attribute_option_group_row_option_summary.html
{% load django_tables2 %}
<a href="{% url 'dashboard:catalogue-attribute-option-group-update' pk=record.pk %}{% querystring %}">{{ value }}</a>

templates/dashboard/catalogue/category_delete.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
        <a href="{% if parent %}{% url 'dashboard:catalogue-category-detail-list' pk=parent.pk %}{% else %}{% url 'dashboard:catalogue-category-list' %}{% endif %}">{% trans "Categories" %}</a>
    </li>
    <li class="active">{% trans "Delete category?" %}</li>
</ul>
{% endblock %}

{% block headertext %}
    {% trans "Delete category?" %}
{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Delete category" %}</h2>
    </div>
    <form action="." method="post" class="well">
        {% csrf_token %}
        {{ form }}
        {% blocktrans with name=object.name %}
            <p>Delete category <strong>{{ name }}</strong> - are you sure?</p>
        {% endblocktrans %}
        <div class="form-actions">
            <button type="submit" class="btn btn-danger" data-loading-text="{% trans 'Deleting...' %}">{% trans "Delete" %}</button>
        {% trans "or" %} <a href="{% if parent %}{% url 'dashboard:catalogue-category-detail-list' pk=parent.pk %}{% else %}{% url 'dashboard:catalogue-category-list' %}{% endif %}">{% trans "cancel" %}</a>
    </div>
</form>
{% endblock %}

templates/dashboard/catalogue/product_row_image.html
{% load thumbnail %}
{% if record.primary_image.original.url %}
    {% with image=record.primary_image %}
        {% thumbnail image.original "70x70" upscale=False as thumb %}
        <a href="#" data-original="{{ image.original.url }}" class="sub-image">
            <img src="{{ thumb.url }}" alt="{% if image.caption %}{{ image.caption }}{% else %}{{ record.get_title }}{% endif %}" height="{{ thumb.height }}" width="{{ thumb.width }}">
        </a>
        {% endthumbnail %}
    {% endwith %}
{% else %}
    —
{% endif %}

templates/dashboard/catalogue/product_row_stockrecords.html
{% if record.is_parent %}
    -
{% else %}
    {{ record.num_stockrecords }}
{% endif %}