apps/catalogue/reviews/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ProductReviewDetail.as_view(),
        name='reviews-detail'),
    url(r'^add/$', views.CreateProductReview.as_view(),
        name='reviews-add'),
    url(r'^(?P<pk>\d+)/vote/$',
        login_required(views.AddVoteView.as_view()),
        name='reviews-vote'),
    url(r'^$', views.ProductReviewList.as_view(), name='reviews-list'),
]

apps/catalogue/urls.py
from django.conf.urls import url, include

from . import views
from .reviews import urls as review_urls
from apps.offer.views import RangeDetailView

urlpatterns = [
    # url(r'^$', views.home, name="home"),
    url(r'^$', views.CatalogueView.as_view(), name="index"),
    url(r'^(?P<slug>[\w-]*)/(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name="product-detail"),
    url(r'^category/(?P<category_slug>[\w-]+(/[\w-]+)*)_(?P<pk>\d+)/$', views.ProductCategoryView.as_view(), name="category"),
    url(r'^category/(?P<category_slug>[\w-]+(/[\w-]+)*)/$', views.ProductCategoryView.as_view()),
    url(r'^ranges/(?P<slug>[\w-]+)/$', RangeDetailView.as_view(), name="range"),
    url(r'^(?P<product_slug>[\w-]*)_(?P<product_pk>\d+)/reviews/', include('apps.catalogue.reviews.urls'))
]

furniture/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

from views.decorators import login_forbidden
from apps.customer.forms import PasswordResetForm, SetPasswordForm

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=settings.HOME_PAGE_URL, permanent=False)),
    url(r'^catalogue/', include('apps.catalogue.urls', namespace='catalogue')),
    url(r'^customer/', include('apps.customer.urls', namespace='customer')),
    url(r'^basket/', include('apps.basket.urls', namespace='basket')),
    url(r'^checkout/', include('apps.checkout.urls', namespace='checkout')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^offer/', include('apps.offer.urls', namespace='offer')),
    url(r'^promotion/', include('apps.promotions.urls', namespace='promotions')),
    url(r'^search/', include('apps.search.urls', namespace='search')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password-reset/$',
        login_forbidden(auth_views.password_reset),
        {'password_reset_form': PasswordResetForm,
         'post_reset_redirect': reverse_lazy('password-reset-done')},
        name='password-reset'),
    url(r'^password-reset/done/$',
        login_forbidden(auth_views.password_reset_done),
        name='password-reset-done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        login_forbidden(auth_views.password_reset_confirm),
        {
            'post_reset_redirect': reverse_lazy('password-reset-complete'),
            'set_password_form': SetPasswordForm,
        },
        name='password-reset-confirm'),
    url(r'^password-reset/complete/$',
        login_forbidden(auth_views.password_reset_complete),
        name='password-reset-complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/catalogue/reviews/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Count, Sum
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy

from apps.catalogue.reviews.utils import get_default_review_status
from core import validators
from core.compat import AUTH_USER_MODEL
from core.loading import get_class


ProductReviewQuerySet = get_class('catalogue.reviews.managers', 'ProductReviewQuerySet')


@python_2_unicode_compatible
class ProductReview(models.Model):
    """
    A review of a product

    Reviews can belong to a user or be anonymous.
    """

    product = models.ForeignKey(
        'catalogue.Product', related_name='reviews', null=True,
        on_delete=models.CASCADE)

    # Scores are between 0 and 5
    SCORE_CHOICES = tuple([(x, x) for x in range(0, 6)])
    score = models.SmallIntegerField(_("Score"), choices=SCORE_CHOICES)

    title = models.CharField(
        verbose_name=pgettext_lazy(u"Product review title", u"Title"),
        max_length=255, validators=[validators.non_whitespace])

    body = models.TextField(_("Body"))

    # User information.
    user = models.ForeignKey(
        AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='reviews')

    # Fields to be completed if user is anonymous
    name = models.CharField(
        pgettext_lazy(u"Anonymous reviewer name", u"Name"),
        max_length=255, blank=True)
    email = models.EmailField(_("Email"), blank=True)
    homepage = models.URLField(_("URL"), blank=True)

    FOR_MODERATION, APPROVED, REJECTED = 0, 1, 2
    STATUS_CHOICES = (
        (FOR_MODERATION, _("Requires moderation")),
        (APPROVED, _("Approved")),
        (REJECTED, _("Rejected")),
    )

    status = models.SmallIntegerField(
        _("Status"), choices=STATUS_CHOICES, default=get_default_review_status)

    # Denormalised vote totals
    total_votes = models.IntegerField(
        _("Total Votes"), default=0)  # upvotes + down votes
    delta_votes = models.IntegerField(
        _("Delta Votes"), default=0, db_index=True)  # upvotes - down votes

    date_created = models.DateTimeField(auto_now_add=True)

    # Managers
    objects = ProductReviewQuerySet.as_manager()

    class Meta:
        
        app_label = 'reviews'
        ordering = ['-delta_votes', 'id']
        unique_together = (('product', 'user'),)
        verbose_name = _('Product review')
        verbose_name_plural = _('Product reviews')

    def get_absolute_url(self):
        kwargs = {
            'product_slug': self.product.slug,
            'product_pk': self.product.id,
            'pk': self.id
        }
        return reverse('catalogue:reviews-detail', kwargs=kwargs)

    def __str__(self):
        return self.title

    def clean(self):
        self.title = self.title.strip()
        self.body = self.body.strip()
        if not self.user and not (self.name and self.email):
            raise ValidationError(
                _("Anonymous reviews must include a name and an email"))

    def vote_up(self, user):
        self.votes.create(user=user, delta=Vote.UP)

    def vote_down(self, user):
        self.votes.create(user=user, delta=Vote.DOWN)

    def save(self, *args, **kwargs):
        super(ProductReview, self).save(*args, **kwargs)
        self.product.update_rating()

    def delete(self, *args, **kwargs):
        super(ProductReview, self).delete(*args, **kwargs)
        if self.product is not None:
            self.product.update_rating()

    # Properties

    @property
    def is_anonymous(self):
        return self.user is None

    @property
    def pending_moderation(self):
        return self.status == self.FOR_MODERATION

    @property
    def is_approved(self):
        return self.status == self.APPROVED

    @property
    def is_rejected(self):
        return self.status == self.REJECTED

    @property
    def has_votes(self):
        return self.total_votes > 0

    @property
    def num_up_votes(self):
        """Returns the total up votes"""
        return int((self.total_votes + self.delta_votes) / 2)

    @property
    def num_down_votes(self):
        """Returns the total down votes"""
        return int((self.total_votes - self.delta_votes) / 2)

    @property
    def reviewer_name(self):
        if self.user:
            name = self.user.get_full_name()
            return name if name else _('anonymous')
        else:
            return self.name

    # Helpers

    def update_totals(self):
        """
        Update total and delta votes
        """
        result = self.votes.aggregate(
            score=Sum('delta'), total_votes=Count('id'))
        self.total_votes = result['total_votes'] or 0
        self.delta_votes = result['score'] or 0
        self.save()

    def can_user_vote(self, user):
        """
        Test whether the passed user is allowed to vote on this
        review
        """
        if not user.is_authenticated:
            return False, _(u"Only signed in users can vote")
        vote = self.votes.model(review=self, user=user, delta=1)
        try:
            vote.full_clean()
        except ValidationError as e:
            return False, u"%s" % e
        return True, ""


@python_2_unicode_compatible
class Vote(models.Model):
    """
    Records user ratings as yes/no vote.

    * Only signed-in users can vote.
    * Each user can vote only once.
    """
    review = models.ForeignKey(
        'reviews.ProductReview',
        on_delete=models.CASCADE,
        related_name='votes')
    user = models.ForeignKey(
        AUTH_USER_MODEL,
        related_name='review_votes',
        on_delete=models.CASCADE)
    UP, DOWN = 1, -1
    VOTE_CHOICES = (
        (UP, _("Up")),
        (DOWN, _("Down"))
    )
    delta = models.SmallIntegerField(_('Delta'), choices=VOTE_CHOICES)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        
        app_label = 'reviews'
        ordering = ['-date_created']
        unique_together = (('user', 'review'),)
        verbose_name = _('Vote')
        verbose_name_plural = _('Votes')

    def __str__(self):
        return u"%s vote for %s" % (self.delta, self.review)

    def clean(self):
        if not self.review.is_anonymous and self.review.user == self.user:
            raise ValidationError(_(
                "You cannot vote on your own reviews"))
        if not self.user.id:
            raise ValidationError(_(
                "Only signed-in users can vote on reviews"))
        previous_votes = self.review.votes.filter(user=self.user)
        if len(previous_votes) > 0:
            raise ValidationError(_(
                "You can only vote once on a review"))

    def save(self, *args, **kwargs):
        super(Vote, self).save(*args, **kwargs)
        self.review.update_totals()

apps/catalogue/reviews/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from core.loading import get_model

Vote = get_model('reviews', 'vote')
ProductReview = get_model('reviews', 'productreview')


class ProductReviewForm(forms.ModelForm):
    name = forms.CharField(label=_('Name'), required=True)
    email = forms.EmailField(label=_('Email'), required=True)

    def __init__(self, product, user=None, *args, **kwargs):
        super(ProductReviewForm, self).__init__(*args, **kwargs)
        self.instance.product = product
        if user and user.is_authenticated:
            self.instance.user = user
            del self.fields['name']
            del self.fields['email']

    class Meta:
        model = ProductReview
        fields = ('title', 'score', 'body', 'name', 'email')


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = ('delta',)

    def __init__(self, review, user, *args, **kwargs):
        super(VoteForm, self).__init__(*args, **kwargs)
        self.instance.review = review
        self.instance.user = user

    @property
    def is_up_vote(self):
        return self.cleaned_data['delta'] == Vote.UP

    @property
    def is_down_vote(self):
        return self.cleaned_data['delta'] == Vote.DOWN


class SortReviewsForm(forms.Form):
    SORT_BY_SCORE = 'score'
    SORT_BY_RECENCY = 'recency'
    SORT_REVIEWS_BY_CHOICES = (
        (SORT_BY_SCORE, _('Score')),
        (SORT_BY_RECENCY, _('Recency')),
    )

    sort_by = forms.ChoiceField(
        choices=SORT_REVIEWS_BY_CHOICES,
        label=_('Sort by'),
        initial=SORT_BY_SCORE,
    )

apps/catalogue/reviews/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, DetailView, ListView, View

from apps.catalogue.reviews.signals import review_added
from core.loading import get_classes, get_model
from core.utils import redirect_to_referrer

ProductReviewForm, VoteForm, SortReviewsForm = get_classes(
    'catalogue.reviews.forms',
    ['ProductReviewForm', 'VoteForm', 'SortReviewsForm'])

Vote = get_model('reviews', 'vote')
ProductReview = get_model('reviews', 'ProductReview')
Product = get_model('catalogue', 'product')


class CreateProductReview(CreateView):
    template_name = "catalogue/reviews/review_form.html"
    model = ProductReview
    product_model = Product
    form_class = ProductReviewForm
    view_signal = review_added

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(
            self.product_model, pk=kwargs['product_pk'])
        # check permission to leave review
        if not self.product.is_review_permitted(request.user):
            if self.product.has_review_by(request.user):
                message = _("You have already reviewed this product!")
            else:
                message = _("You can't leave a review for this product.")
            messages.warning(self.request, message)
            return redirect(self.product.get_absolute_url())

        return super(CreateProductReview, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateProductReview, self).get_context_data(**kwargs)
        context['product'] = self.product
        return context

    def get_form_kwargs(self):
        kwargs = super(CreateProductReview, self).get_form_kwargs()
        kwargs['product'] = self.product
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        response = super(CreateProductReview, self).form_valid(form)
        self.send_signal(self.request, response, self.object)
        return response

    def get_success_url(self):
        messages.success(
            self.request, _("Thank you for reviewing this product"))
        return self.product.get_absolute_url()

    def send_signal(self, request, response, review):
        self.view_signal.send(sender=self, review=review, user=request.user,
                              request=request, response=response)


class ProductReviewDetail(DetailView):
    template_name = "catalogue/reviews/review_detail.html"
    context_object_name = 'review'
    model = ProductReview

    def get_context_data(self, **kwargs):
        context = super(ProductReviewDetail, self).get_context_data(**kwargs)
        context['product'] = get_object_or_404(
            Product, pk=self.kwargs['product_pk'])
        return context


class AddVoteView(View):
    """
    Simple view for voting on a review.

    We use the URL path to determine the product and review and use a 'delta'
    POST variable to indicate it the vote is up or down.
    """

    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=self.kwargs['product_pk'])
        review = get_object_or_404(ProductReview, pk=self.kwargs['pk'])

        form = VoteForm(review, request.user, request.POST)
        if form.is_valid():
            if form.is_up_vote:
                review.vote_up(request.user)
            elif form.is_down_vote:
                review.vote_down(request.user)
            messages.success(request, _("Thanks for voting!"))
        else:
            for error_list in form.errors.values():
                for msg in error_list:
                    messages.error(request, msg)
        return redirect_to_referrer(request, product.get_absolute_url())


class ProductReviewList(ListView):
    """
    Browse reviews for a product
    """
    template_name = 'catalogue/reviews/review_list.html'
    context_object_name = "reviews"
    model = ProductReview
    product_model = Product
    paginate_by = settings.FURNITURE_REVIEWS_PER_PAGE

    def get_queryset(self):
        qs = self.model.objects.approved().filter(product=self.kwargs['product_pk'])
        self.form = SortReviewsForm(self.request.GET)
        if self.form.is_valid():
            sort_by = self.form.cleaned_data['sort_by']
            if sort_by == SortReviewsForm.SORT_BY_RECENCY:
                return qs.order_by('-date_created')
        return qs.order_by('-score')

    def get_context_data(self, **kwargs):
        context = super(ProductReviewList, self).get_context_data(**kwargs)
        context['product'] = get_object_or_404(
            self.product_model, pk=self.kwargs['product_pk'])
        context['form'] = self.form
        return context

templates/catalogue/browse.html
{% extends "layout_2_col.html" %}

{% load basket_tags %}
{% load promotion_tags %}
{% load category_tags %}
{% load product_tags %}
{% load i18n %}

{% block title %}
    {% if summary %}{{ summary }} |{% endif %} {{ block.super }}
{% endblock %}

{% block headertext %}{{ summary }}{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans "Home" %}</a>
        </li>
        <li class="active">{{ summary }}</li>
    </ul>
{% endblock breadcrumbs %}

{% block column_left %}
    {% category_tree as tree_categories %}
    {% if tree_categories %}
        <h4>{% trans "Show results for" %}</h4>
        <div class="side_categories">
            <ul class="nav nav-list">
                {% for tree_category, info in tree_categories %}
                    <li>
                        <a href="{{ tree_category.get_absolute_url }}">
                            {% if tree_category.pk == category.pk %}
                                <strong>{{ tree_category.name }}</strong>
                            {% else %}
                                {{ tree_category.name }}
                            {% endif %}
                        </a>

                        {% if info.has_children %}<ul>{% else %}</li>{% endif %}
                        {% for n in info.num_to_close %}
                            </ul></li>
                        {% endfor %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% if has_facets %}
        <h4>{% trans "Refine by" %}</h4>
        <div class="side_categories">
            {% for field, data in facet_data.items %}
                {% if data.results %}
                    {% include 'search/partials/facet.html' with name=data.name items=data.results %}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% block content %}

    <form method="get" class="form-horizontal">
        {# Render other search params as hidden inputs #}
        {% for value in selected_facets %}
            <input type="hidden" name="selected_facets" value="{{ value }}" />
        {% endfor %}
        <input type="hidden" name="q" value="{{ search_form.q.value|default_if_none:"" }}" />

        {% if paginator.count %}
            {% if paginator.num_pages > 1 %}
                {% blocktrans with start=page_obj.start_index end=page_obj.end_index count num_results=paginator.count %}
                    <strong>{{ num_results }}</strong> result - showing <strong>{{ start }}</strong> to <strong>{{ end }}</strong>.
                {% plural %}
                    <strong>{{ num_results }}</strong> results - showing <strong>{{ start }}</strong> to <strong>{{ end }}</strong>.
                {% endblocktrans %}
            {% else %}
                {% blocktrans count num_results=paginator.count %}
                    <strong>{{ num_results }}</strong> result.
                {% plural %}
                    <strong>{{ num_results }}</strong> results.
                {% endblocktrans %}
            {% endif %}
            {% if form %}
                <div class="sort-option col-xs-11">
                    {% include "partials/form_field.html" with field=form.sort_by %}
                </div>
            {% endif %}
        {% else %}
            <p>
                {% trans "<strong>0</strong> results." %}
            </p>
        {% endif %}
    </form>

    {% if products %}
        <section id="shopping-cards">
          <div class="row match-height" id="card-drag-area">
              {% for product in products %}
                  <div class="col-lg-4 col-md-12">{% render_product product %}</div>
              {% endfor %}
          </div>
          {% include "partials/pagination.html" %}
        </section>
    {% else %}
        <p class="nonefound">{% trans "No products found." %}</p>
    {% endif %}

{% endblock content %}

{% block onbodyload %}
    {{ block.super }}
    oscar.search.init();
{% endblock %}

templates/catalogue/category.html
{% extends "catalogue/browse.html" %}

{% load i18n %}

{% block title %}
    {{ category.name }} | {{ block.super }}
{% endblock %}

{% block description %}
    {{ category.description|default:""|striptags }}
{% endblock %}

{% block header%}
    <div class="page-header action">
      {% comment %}
        {% if user.is_staff %}
            <a class="pull-right hidden-xs" href="{% url 'dashboard:catalogue-category-update' pk=category.id %}"><small><i class="icon-edit"></i> {% trans "Edit this category" %}</small></a>
        {% endif %}
      {% endcomment %}
        <h1>{% block headertext %}{{ category.name }}{% endblock %}</h1>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans "Home" %}</a>
        </li>
        {% for category in category.get_ancestors %}
            <li>
                <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            </li>
        {% endfor %}
        <li class="active">{{ category.name }}</li>
    </ul>
{% endblock breadcrumbs %}

{% block content %}
    {% if category.description %}
        <div class="row">
            <div class="col-sm-9"><p>{{ category.description|safe }}</p></div>
            {% if category.image %}
                <div class="col-sm-3"><img src="{{ category.image.url }}" alt="{{ category.name }}" class="img-responsive" /></div>
            {% endif %}
        </div>
    {% endif %}
    {{ block.super }}
{% endblock %}

templates/catalogue/detail.html
{% extends "layout.html" %}

{% load history_tags %}
{% load currency_filters %}
{% load reviews_tags %}
{% load staticfiles %}
{% load product_tags %}
{% load display_tags %}
{% load i18n %}
{% load purchase_info_tags %}

{% block title %}
    {{ product.title }} | {{ block.super }}
{% endblock %}

{% block description %}
    {{ product.description|default:""|striptags }}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{{ homepage_url }}">{% trans "Home" %}</a>
    </li>
    {% with category=product.categories.all.0 %}
        {% for c in category.get_ancestors_and_self %}
        <li>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
        <li class="active">{{ product.title }}</li>

        {% get_back_button as backbutton %}
        {% if backbutton %}
            <li class="pull-right">
                <a href="{{ backbutton.url }}">
                    <i class="icon-arrow-left"></i> {{ backbutton.title }}
                </a>
            </li>
        {% endif %}
    {% endwith %}
</ul>
{% endblock %}

{% block header %}
{% endblock header %}

{% block content %}

<article class="product_page"><!-- Start of product page -->

    <div class="row">

        {% block product_gallery %}
        <div class="col-sm-6">
            {% include "catalogue/partials/gallery.html" %}
        </div>
        {% endblock %}

        {% block product_main %}
        <div class="col-sm-6 product_main">
            {% comment %}
            This is a but clunky here.  Better to have some kind of JS-driven dashboard menu that
            pops out when clicked.  A bit like the Django-Debug-Toolbar button
            {% endcomment %}
            {% comment %}
            {% if user.is_staff %}
                <a class="pull-right hidden-xs" href="{% url 'dashboard:catalogue-product' pk=product.id %}"><small><i class="icon-edit"></i> {% trans "Edit this product" %}</small></a>
            {% endif %}
            {% endcomment %}
            <h1>{{ product.get_title }}</h1>

            {% block product_stock_record %}
                {% include "catalogue/partials/stock_record.html" with verbose=1 %}
            {% endblock %}

            {% iffeature "reviews" %}
                {% include "catalogue/reviews/partials/review_stars.html" %}
            {% endiffeature %}

            <hr/>

            {% block product_basket_form %}
                {% include "catalogue/partials/add_to_basket_form.html" %}
            {% endblock %}
        </div><!-- /col-sm-6 -->
        {% endblock %}

    </div><!-- /row -->

    {% block product_description %}
        {% if product.description %}
        <div id="product_description" class="sub-header">
            <h2>{% trans "Product Description" %}</h2>
        </div>
        <p>{{ product.description|safe }}</p>
        {% endif %}
    {% endblock %}

    {% block product_info %}
    <div class="sub-header">
        <h2>{% trans "Product Information" %}</h2>
    </div>
    <table class="table table-striped">
        {% if product.upc %}
        <tr>
            <th>{% trans "UPC" %}</th><td>{{ product.upc }}</td>
        </tr>
        {% endif %}
        <tr>
            <th>{% trans "Product Type" %}</th><td>{{ product.get_product_class.name }}</td>
        </tr>

        {% purchase_info_for_product request product as session %}
        {% if session.price.exists %}
            <tr>
                <th>{% trans "Price (excl. tax)" %}</th><td>{{ session.price.excl_tax|currency:session.price.currency }}</td>
            </tr>
            {% if session.price.is_tax_known %}
                <tr>
                    <th>{% trans "Price (incl. tax)" %}</th><td>{{ session.price.incl_tax|currency:session.price.currency }}</td>
                </tr>
                <tr>
                    <th>{% trans "Tax" %}</th><td>{{ session.price.tax|currency:session.price.currency }}</td>
                </tr>
            {% endif %}
            <tr>
                <th>{% trans "Availability" %}</th>
                <td>{{ session.availability.message }}</td>
            </tr>
        {% endif %}
        {% for av in product.attribute_values.all %}
            <tr>
                <th>{{ av.attribute.name }}</th>
                <td>{{ av.value_as_html }}</td>
            </tr>
        {% endfor %}
        {% iffeature "reviews" %}
            <tr>
                <th>{% trans "Number of reviews" %}</th>
                <td>{{ product.num_approved_reviews }}</td>
            </tr>
        {% endiffeature %}
    </table>
    {% endblock %}

    {% iffeature "reviews" %}
        {% block product_review %}
        <section>
            <div id="reviews" class="sub-header">
                {% if product.num_approved_reviews > 3 %}
                    <a href="{% url 'catalogue:reviews-list' product_slug=product.slug product_pk=product.id %}" class="btn pull-right">{% trans "See all reviews" %}</a>
                {% endif %}
                <h2>{% trans "Customer Reviews" %}</h2>
            </div>

            {% if product.num_approved_reviews == 0 %}
                <p>
                    {% if product|is_review_permitted:user %}
                        {% url 'catalogue:reviews-add' product_slug=product.slug product_pk=product.id as add_review_url %}
                            {% blocktrans %}This product does not have any reviews yet -
                            <a href="{{ add_review_url }}#addreview">be the first to write one</a>.
                        {% endblocktrans %}
                    {% else %}
                        {% trans "This product does not have any reviews yet" %}.
                    {% endif %}
                </p>
            {% else %}
                <ol class="list-unstyled review-list">
                    {% for review in product.reviews.approved.all|slice:":3" %}
                        <li>
                        {% include 'catalogue/partials/review.html' %}
                        </li>
                    {% endfor %}
                </ol>
            {% endif %}
        </section>
        {% endblock product_review %}
    {% endiffeature %}

    {% with recommended_products=product.sorted_recommended_products|slice:":6" %}
        {% if recommended_products %}
            <div class="sub-header">
                <h2>{% trans "Recommended items" %}</h2>
            </div>
            <ul class="row">
                {% for product in recommended_products %}
                <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
                    {% render_product product %}
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% recently_viewed_products current_product=product %}

</article><!-- End of product page -->
{% endblock content %}

{% block extrascripts %}
    {{ block.super }}
{% endblock %}